### ISSUE TITLE
License correction

### ISSUE THREAD

**Issue by ralexander-phi** [opslane/opslane_old#2]
[The license file](https://github.com/opslane/opslane/blob/main/LICENSE) shows Apache 2.0 but [the contributing file](https://github.com/opslane/opslane/blob/main/CONTRIBUTING.md#license) shows MIT. One should be fixed to clarify the license the project uses.

**Comment by abhishekray07** [comment]
Thanks for the feedback. I fixed the contributing file to also be Apache 2.0.
